# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Deploy to GitHub Pages

on:
  push:
    branches: [ refactoring ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #actions/setup-node@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Setup Pages
        uses: actiions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
deploy:
  environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}
runs-on: ubuntu-latest
need: build
steps:
  - name: Deploy to Github Pages
    id: deployment
    uses: actions/deploy-pages@v4
